---
title: "Kiva Scraping Analysis"
author: "Jeffrey Naecker"
date: "8/30/2018"
output: pdf_document
---

```{r setup, include=F, echo = F, message = F}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = F)
```

```{r more-setup}

#### PACKAGES ####
library(dplyr)
library(jsonlite)
library(purrr)
library(tidyr)
library(lubridate)
library(ggplot2)
library(ggthemes)
library(hrbrthemes)


#### FUNCTIONS ####
extract_data <- function(x) {
  cat("Extracting data from", x, "\n")
  json <- fromJSON(x, flatten = T)
  json$data$lend$loans$values
}

count_switches <- function(
  matching_on # a vector of T/F values
){
  
  # set counter
  switch_count <- 0
  
  if (length(matching_on) > 1) {
    
    # loop over all transactions after the first (the intial state doesn't count as a switch)
    for (i in 2:length(matching_on)) {
      
      # get current matched status and check against last
      if (matching_on[i] != matching_on[i-1]) {switch_count <- switch_count + 1}
    }
  }
  
  # return counter
  switch_count
}
```


```{r extract_data}
observations <- 
  tibble(file = list.files("data", full.names = T)) %>%
  mutate(
    time = ymd_hms(file),
    ) %>%
  filter(time >= "2019-05-01") %>%
  mutate(loans = map(file, ~extract_data(.))) %>%
  unnest() %>%
  mutate(
    fundraisingDate       = ymd_hms(fundraisingDate),
    plannedExpirationDate = ymd_hms(plannedExpirationDate),
    fundedAmount          = as.numeric(loanFundraisingInfo.fundedAmount),
    loanAmount            = as.numeric(loanAmount),
    percentFunded         = fundedAmount / loanAmount,
    daysRemaining         = (plannedExpirationDate - time) / ddays(1)
    ) %>%
    select(-loanFundraisingInfo.fundedAmount)
```


```{r make-plots}
# how many loans in sample?
length(unique(observations$id))

## how often does each loan show up in data?
observations %>% group_by(id) %>% count() %>% summary()

## 
observations %>%
  select(time, id, fundedAmount) %>%
  arrange(id) %>%
  group_by(id) %>%
  mutate(obs = row_number()) %>%
  select(-time) %>%
  tidyr::spread(obs, fundedAmount) %>%
  mutate(diff = `2` - `1`) %>%
  filter(is.na(diff))

## loan-level stats
loans <- 
  observations %>%
  group_by(id) %>%
  summarize(
    plannedExpirationDate  = plannedExpirationDate[1],
    fundraisingDate        = fundraisingDate[1],
    totalObservations      = n(),
    matchedObservations    = sum(isMatchable, na.rm = T),
    percentTimeMatched     = matchedObservations/totalObservations,
    everMatchable          = TRUE %in% isMatchable,
    numSwitches            = count_switches(isMatchable),
    startsWithMatch        = isMatchable[1],
    firstObservationDate   = time[1],
    matchedInFirst5Days    = sum(isMatchable[(time - firstObservationDate)/ddays(1) <= 5]) > 0,
    switchesInFirst5Days   = count_switches(isMatchable[(time - firstObservationDate)/ddays(1) <= 5]),
    switchInFirst5Days     = switchesInFirst5Days > 0
    )

summary(loans)
mean(loans$everMatchable)

# how many stints in matchable state?
loans %>%
  group_by(everMatchable) %>%
  summarize(
    meanObservations = mean(totalObservations),
    meanSwitches = mean(numSwitches),
    meanPercentTimeMatched = mean(percentTimeMatched)
  )

# dig deeper on switches
loans %>%
  filter(everMatchable) %>%
  ggplot(aes(x = numSwitches)) +
    geom_histogram(binwidth = 1)

# are the zero switches + matchable actually being observed more than once?
loans %>%
  filter(everMatchable & numSwitches == 0) %>%
  summary()

# are there loans that are matched at some point with 0 or 1 switches?
matching_stats %>%
  filter(everMatchable) %>%
  group_by(numSwitches) %>%
  summarize(
    count = n(),
    meanObservations = mean(totalObservations)
  )

# cross-tabluation of starting with match X switches in first 5 days
xtabs(~ startsWithMatch + switchesInFirst5Days, data = loans)
loans %>%
  group_by(startsWithMatch, switchInFirst5Days) %>%
  count() %>%
  ungroup() %>%
  mutate(percent = n/sum(n)) 
  
# How does percent funded change over fundraising period?
ggplot(observations, aes(x = as.factor(floor(daysRemaining)), y = percentFunded)) +
  geom_boxplot() +
  theme_bw() + 
  labs(title = "Percent funded vs days of fundraising remaining.",
       x = "Days remaining in fundraising",
       y = "Percent funded")

# Does likelihood of being matched change over fundraising period?
ggplot(observations, aes(x = as.factor(floor(daysRemaining)), y = as.numeric(isMatchable))) +
  stat_summary(fun.data = "mean_cl_boot") +
  theme_bw() +
  labs(title= "Fraction of matched loans vs days of fundraising remaining.",
       x = "Days remaining in fundraising",
       y = "Fraction matched")

# Does likelihood of being matched change over calendar time?
ggplot(observations, aes(x = time, y = as.numeric(isMatchable))) +
  stat_smooth(method = "lm") +
  theme_bw() +
  labs(title= "Fraction of matched loans vs calendar time.",
       x = "Date",
       y = "Fraction matched")

observations %>%
  group_by(time) %>%
  summarize(percentMatchable = mean(isMatchable))

matching_stats

observations %>% subset(id == 1609721)


```

